In [4]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('students.csv')
# print(df)
df.head(2)
df.tail(2)
df.shape
df.columns

Index(['student_id', 'name', 'age', 'city', 'course', 'marks'], dtype='str')

In [29]:
df.rename(columns={'marks' : 'monthly_marks'})
df.info()
df.describe()
df.shape
df.ndim
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  20 non-null     int64
 1   name        20 non-null     str
 2   age         20 non-null     int64
 3   city        20 non-null     str
 4   course      20 non-null     str
 5   marks       20 non-null     int64
dtypes: int64(3), str(3)
memory usage: 1.1 KB

student_id    int64
name            str
age           int64
city            str
course          str
marks         int64
dtype: object

In [31]:
df.head(5)

   student_id           name  age       city   course  marks
0           1    Aarav Patel   20  Ahmedabad  IMSc IT     85
1           2      Diya Shah   21      Surat      BCA     91
2           3   Vivaan Mehta   20   Vadodara  IMSc IT     78
3           4    Anaya Desai   22     Rajkot   BSc CS     88
4           5  Reyansh Joshi   19  Ahmedabad      BCA     73

In [37]:
df.iloc[1]
df.loc[df["age"] == 20]

    student_id            name  age         city   course  marks
0            1     Aarav Patel   20    Ahmedabad  IMSc IT     85
2            3    Vivaan Mehta   20     Vadodara  IMSc IT     78
6            7      Advik Shah   20        Surat   BSc CS     67
10          11     Krish Patel   20     Vadodara      BCA     92
14          15  Atharv Trivedi   20  Gandhinagar  IMSc IT     70
18          19      Rudra Shah   20     Vadodara   BSc CS     58

In [39]:
print("Pandas Series:")
series = pd.Series(df['marks'])
print(series)

print("\nDataFrame:")
print(df)

Pandas Series:
0     85
1     91
2     78
3     88
4     73
5     95
6     67
7     82
8     76
9     89
10    92
11    81
12    64
13    97
14    70
15    86
16    79
17    93
18    58
19    84
Name: marks, dtype: int64

DataFrame:
    student_id            name  age         city   course  marks
0            1     Aarav Patel   20    Ahmedabad  IMSc IT     85
1            2       Diya Shah   21        Surat      BCA     91
2            3    Vivaan Mehta   20     Vadodara  IMSc IT     78
3            4     Anaya Desai   22       Rajkot   BSc CS     88
4            5   Reyansh Joshi   19    Ahmedabad      BCA     73
5            6    Isha Trivedi   21  Gandhinagar  IMSc IT     95
6            7      Advik Shah   20        Surat   BSc CS     67
7            8      Sara Patel   22    Bhavnagar      BCA     82
8            9    Arjun Parmar   19    Ahmedabad  IMSc IT     76
9           10       Myra Shah   21        Anand   BSc CS     89
10          11     Krish Patel   20     Vadodara      BCA     92
11          12    Aadhya Mehta   22        Surat  IMSc IT     81
12          13     Dhruv Joshi   19       Rajkot   BSc CS     64
13          14     Kiara Desai   21    Ahmedabad      BCA     97
14          15  Atharv Trivedi   20  Gandhinagar  IMSc IT     70
15          16    Navya Parmar   22    Bhavnagar   BSc CS     86
16          17     Kabir Mehta   19        Anand      BCA     79
17          18    Saanvi Patel   21        Surat  IMSc IT     93
18          19      Rudra Shah   20     Vadodara   BSc CS     58
19          20      Pari Joshi   22    Ahmedabad      BCA     84