In [10]:
import numpy as np
import pandas as pd

df = pd.read_csv("ecommerce.csv")
print(df.head(5).to_string(index=False))

# Display shape, dtypes, head(), and tail().
print(df.shape)
print(df.dtypes)
print(df.head(),df.tail())

 Order_ID Customer_Name       Product    Category Region  Quantity  Price Payment_Mode
     1001   Aarav Patel        Laptop Electronics   West         1  65000  Credit Card
     1002     Diya Shah    Headphones Electronics  North         2   2500          UPI
     1003   Rohan Mehta    Smartphone Electronics  South         1  42000   Debit Card
     1004   Anaya Desai       T-shirt    Clothing   West         3    799          UPI
     1005  Vivaan Joshi Running Shoes    Footwear   East         1   3500         Cash
(15, 8)
Order_ID         int64
Customer_Name      str
Product            str
Category           str
Region             str
Quantity         int64
Price            int64
Payment_Mode       str
dtype: object
   Order_ID Customer_Name        Product     Category Region  Quantity  Price  \
0      1001   Aarav Patel         Laptop  Electronics   West         1  65000
1      1002     Diya Shah     Headphones  Electronics  North         2   2500
2      1003   Rohan Mehta     Smartphone  Electronics  South         1  42000
3      1004   Anaya Desai        T-shirt     Clothing   West         3    799
4      1005  Vivaan Joshi  Running Shoes     Footwear   East         1   3500

  Payment_Mode
0  Credit Card
1          UPI
2   Debit Card
3          UPI
4         Cash       Order_ID  Customer_Name         Product        Category Region  Quantity  \
10      1011    Arjun Joshi          Tablet     Electronics  South         1
11      1012  Kiara Trivedi    Water Bottle  Home & Kitchen   West         3
12      1013      Dev Patel         Monitor     Electronics   East         1
13      1014     Aanya Shah        Sneakers        Footwear  North         1
14      1015  Reyansh Mehta  Wireless Mouse     Accessories   West         2

    Price Payment_Mode
10  28000  Credit Card
11    499         Cash
12  14500  Net Banking
13   3200   Debit Card
14   1200          UPI

In [ ]:
# Rename Customer_Name to Customer and Payment_Mode to Payment.
df.rename(columns={"Customer_Name" : "Customer",
                   "Payment_Mode" : "Payment"})

,Order_ID,Customer,Product,Category,Region,Quantity,Price,Payment
0,1001,Aarav Patel,Laptop,Electronics,West,1,65000,Credit Card
1,1002,Diya Shah,Headphones,Electronics,North,2,2500,UPI
2,1003,Rohan Mehta,Smartphone,Electronics,South,1,42000,Debit Card
3,1004,Anaya Desai,T-shirt,Clothing,West,3,799,UPI
4,1005,Vivaan Joshi,Running Shoes,Footwear,East,1,3500,Cash
5,1006,Isha Trivedi,Coffee Maker,Home Appliances,North,1,4500,Credit Card
6,1007,Krish Patel,Backpack,Accessories,West,2,1800,UPI
7,1008,Myra Shah,Smartwatch,Electronics,South,1,8500,Debit Card
8,1009,Aditya Mehta,Keyboard,Electronics,East,2,2200,Net Banking
9,1010,Sara Desai,Jeans,Clothing,North,2,1999,UPI
10,1011,Arjun Joshi,Tablet,Electronics,South,1,28000,Credit Card
11,1012,Kiara Trivedi,Water Bottle,Home & Kitchen,West,3,499,Cash
12,1013,Dev Patel,Monitor,Electronics,East,1,14500,Net Banking
13,1014,Aanya Shah,Sneakers,Footwear,North,1,3200,Debit Card
14,1015,Reyansh Mehta,Wireless Mouse,Accessories,West,2,1200,UPI

In [ ]:
df["Quantity"] = df["Quantity"].astype(float)
print(df)

    Order_ID  Customer_Name         Product         Category Region  Quantity  \
0       1001    Aarav Patel          Laptop      Electronics   West       1.0
1       1002      Diya Shah      Headphones      Electronics  North       2.0
2       1003    Rohan Mehta      Smartphone      Electronics  South       1.0
3       1004    Anaya Desai         T-shirt         Clothing   West       3.0
4       1005   Vivaan Joshi   Running Shoes         Footwear   East       1.0
5       1006   Isha Trivedi    Coffee Maker  Home Appliances  North       1.0
6       1007    Krish Patel        Backpack      Accessories   West       2.0
7       1008      Myra Shah      Smartwatch      Electronics  South       1.0
8       1009   Aditya Mehta        Keyboard      Electronics   East       2.0
9       1010     Sara Desai           Jeans         Clothing  North       2.0
10      1011    Arjun Joshi          Tablet      Electronics  South       1.0
11      1012  Kiara Trivedi    Water Bottle   Home & Kitchen   West       3.0
12      1013      Dev Patel         Monitor      Electronics   East       1.0
13      1014     Aanya Shah        Sneakers         Footwear  North       1.0
14      1015  Reyansh Mehta  Wireless Mouse      Accessories   West       2.0

    Price Payment_Mode
0   65000  Credit Card
1    2500          UPI
2   42000   Debit Card
3     799          UPI
4    3500         Cash
5    4500  Credit Card
6    1800          UPI
7    8500   Debit Card
8    2200  Net Banking
9    1999          UPI
10  28000  Credit Card
11    499         Cash
12  14500  Net Banking
13   3200   Debit Card
14   1200          UPI

In [ ]:
df['Total_Amount'] = df['Quantity'] * df['Price']
print(df)

    Order_ID  Customer_Name         Product         Category Region  Quantity  \
0       1001    Aarav Patel          Laptop      Electronics   West       1.0
1       1002      Diya Shah      Headphones      Electronics  North       2.0
2       1003    Rohan Mehta      Smartphone      Electronics  South       1.0
3       1004    Anaya Desai         T-shirt         Clothing   West       3.0
4       1005   Vivaan Joshi   Running Shoes         Footwear   East       1.0
5       1006   Isha Trivedi    Coffee Maker  Home Appliances  North       1.0
6       1007    Krish Patel        Backpack      Accessories   West       2.0
7       1008      Myra Shah      Smartwatch      Electronics  South       1.0
8       1009   Aditya Mehta        Keyboard      Electronics   East       2.0
9       1010     Sara Desai           Jeans         Clothing  North       2.0
10      1011    Arjun Joshi          Tablet      Electronics  South       1.0
11      1012  Kiara Trivedi    Water Bottle   Home & Kitchen   West       3.0
12      1013      Dev Patel         Monitor      Electronics   East       1.0
13      1014     Aanya Shah        Sneakers         Footwear  North       1.0
14      1015  Reyansh Mehta  Wireless Mouse      Accessories   West       2.0

    Price Payment_Mode  Total_Amount
0   65000  Credit Card       65000.0
1    2500          UPI        5000.0
2   42000   Debit Card       42000.0
3     799          UPI        2397.0
4    3500         Cash        3500.0
5    4500  Credit Card        4500.0
6    1800          UPI        3600.0
7    8500   Debit Card        8500.0
8    2200  Net Banking        4400.0
9    1999          UPI        3998.0
10  28000  Credit Card       28000.0
11    499         Cash        1497.0
12  14500  Net Banking       14500.0
13   3200   Debit Card        3200.0
14   1200          UPI        2400.0

In [23]:
df[(df['Total_Amount'] > 2000) & (df['Quantity'] > 1)]

,Order_ID,Customer_Name,Product,Category,Region,Quantity,Price,Payment_Mode,Total_Amount
1,1002,Diya Shah,Headphones,Electronics,North,2.0,2500,UPI,5000.0
3,1004,Anaya Desai,T-shirt,Clothing,West,3.0,799,UPI,2397.0
6,1007,Krish Patel,Backpack,Accessories,West,2.0,1800,UPI,3600.0
8,1009,Aditya Mehta,Keyboard,Electronics,East,2.0,2200,Net Banking,4400.0
9,1010,Sara Desai,Jeans,Clothing,North,2.0,1999,UPI,3998.0
14,1015,Reyansh Mehta,Wireless Mouse,Accessories,West,2.0,1200,UPI,2400.0

In [24]:
df[(df["Region"] == "North") | (df["Region"] == "South")]

,Order_ID,Customer_Name,Product,Category,Region,Quantity,Price,Payment_Mode,Total_Amount
1,1002,Diya Shah,Headphones,Electronics,North,2.0,2500,UPI,5000.0
2,1003,Rohan Mehta,Smartphone,Electronics,South,1.0,42000,Debit Card,42000.0
5,1006,Isha Trivedi,Coffee Maker,Home Appliances,North,1.0,4500,Credit Card,4500.0
7,1008,Myra Shah,Smartwatch,Electronics,South,1.0,8500,Debit Card,8500.0
9,1010,Sara Desai,Jeans,Clothing,North,2.0,1999,UPI,3998.0
10,1011,Arjun Joshi,Tablet,Electronics,South,1.0,28000,Credit Card,28000.0
13,1014,Aanya Shah,Sneakers,Footwear,North,1.0,3200,Debit Card,3200.0

In [27]:
df.query("Price > 5000")

,Order_ID,Customer_Name,Product,Category,Region,Quantity,Price,Payment_Mode,Total_Amount
0,1001,Aarav Patel,Laptop,Electronics,West,1.0,65000,Credit Card,65000.0
2,1003,Rohan Mehta,Smartphone,Electronics,South,1.0,42000,Debit Card,42000.0
7,1008,Myra Shah,Smartwatch,Electronics,South,1.0,8500,Debit Card,8500.0
10,1011,Arjun Joshi,Tablet,Electronics,South,1.0,28000,Credit Card,28000.0
12,1013,Dev Patel,Monitor,Electronics,East,1.0,14500,Net Banking,14500.0

In [34]:
df[df["Category"].isin(["Electronics", "Footwear"])]

,Order_ID,Customer_Name,Product,Category,Region,Quantity,Price,Payment_Mode,Total_Amount
0,1001,Aarav Patel,Laptop,Electronics,West,1.0,65000,Credit Card,65000.0
1,1002,Diya Shah,Headphones,Electronics,North,2.0,2500,UPI,5000.0
2,1003,Rohan Mehta,Smartphone,Electronics,South,1.0,42000,Debit Card,42000.0
4,1005,Vivaan Joshi,Running Shoes,Footwear,East,1.0,3500,Cash,3500.0
7,1008,Myra Shah,Smartwatch,Electronics,South,1.0,8500,Debit Card,8500.0
8,1009,Aditya Mehta,Keyboard,Electronics,East,2.0,2200,Net Banking,4400.0
10,1011,Arjun Joshi,Tablet,Electronics,South,1.0,28000,Credit Card,28000.0
12,1013,Dev Patel,Monitor,Electronics,East,1.0,14500,Net Banking,14500.0
13,1014,Aanya Shah,Sneakers,Footwear,North,1.0,3200,Debit Card,3200.0

In [37]:
df[df["Customer_Name"].str.startswith("R")]

,Order_ID,Customer_Name,Product,Category,Region,Quantity,Price,Payment_Mode,Total_Amount
2,1003,Rohan Mehta,Smartphone,Electronics,South,1.0,42000,Debit Card,42000.0
14,1015,Reyansh Mehta,Wireless Mouse,Accessories,West,2.0,1200,UPI,2400.0

In [38]:
df.drop(columns=["Region"])

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Payment_Mode,Total_Amount
0,1001,Aarav Patel,Laptop,Electronics,1.0,65000,Credit Card,65000.0
1,1002,Diya Shah,Headphones,Electronics,2.0,2500,UPI,5000.0
2,1003,Rohan Mehta,Smartphone,Electronics,1.0,42000,Debit Card,42000.0
3,1004,Anaya Desai,T-shirt,Clothing,3.0,799,UPI,2397.0
4,1005,Vivaan Joshi,Running Shoes,Footwear,1.0,3500,Cash,3500.0
5,1006,Isha Trivedi,Coffee Maker,Home Appliances,1.0,4500,Credit Card,4500.0
6,1007,Krish Patel,Backpack,Accessories,2.0,1800,UPI,3600.0
7,1008,Myra Shah,Smartwatch,Electronics,1.0,8500,Debit Card,8500.0
8,1009,Aditya Mehta,Keyboard,Electronics,2.0,2200,Net Banking,4400.0
9,1010,Sara Desai,Jeans,Clothing,2.0,1999,UPI,3998.0
10,1011,Arjun Joshi,Tablet,Electronics,1.0,28000,Credit Card,28000.0
11,1012,Kiara Trivedi,Water Bottle,Home & Kitchen,3.0,499,Cash,1497.0
12,1013,Dev Patel,Monitor,Electronics,1.0,14500,Net Banking,14500.0
13,1014,Aanya Shah,Sneakers,Footwear,1.0,3200,Debit Card,3200.0
14,1015,Reyansh Mehta,Wireless Mouse,Accessories,2.0,1200,UPI,2400.0